#!/bin/bash

#[ -x ~/.xinitrc ] && ~/.xinitrc

declare -a startonce=(
  "sxhkd -m -1"

  "compton --config $HOME/.config/compton/compton.conf"
  "$HOME/.config/polybar/launch.sh"

  "nm-applet"
  "pasystray"
  "autokey-gtk"

  "nitrogen --restore"

  "xmodmap $HOME/.Xmodmap"

  "/usr/lib/gnome-settings-daemon/gsd-xsettings"

  # Clipboard history
  "greenclip daemon"
  "dropbox start"

  # Not sure why this is necessary
  "xrdb -load $HOME/.Xresources"
  "xautolock -detectsleep -locker 'betterlockscreen -l'"
)

declare -a nousr1=(
  xautolock greenclip dropbox nm-applet nitrogen
)

for cmd in "${startonce[@]}" ; do
  split=($cmd)
  basecmd="$(basename ${split[0]})"
  if pgrep -x "${basecmd}" ; then
    # xautolock doesn't handle usr1 properly
    if [[ ! "${nousr1[@]}" =~ "${basecmd}" ]] ; then
      pkill -USR1 -x "${basecmd}"
    fi
  else
    ${cmd} &
  fi
done

dunst &

# xsetroot -cursor_name left_ptr &

#padding
bspc config top_padding        0
bspc config bottom_padding     62
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       0
bspc config window_gap         20

# Borders and gaps
bspc config borderless_monocle true
bspc config gapless_monocle true

# Border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#FFFFFF"
#B0BEC5

#presel color
bspc config presel_feedback_color "#B0BEC5"

# Focusing behavior
bspc config focus_follows_pointer true
#bspc config history_aware_focus true
#bspc config focus_by_distance true

# Misc
bspc config split_ratio 0.62
#bspc config auto_cancel true

# Split to right
bspc config initial_polarity second_child

#mouse options for floating windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6
