#!/bin/bash

set -e

# Multi-monitor setup
MONITORS=($(bspc query -M --names))

if [[ ${#MONITORS} == "1" ]] ; then
  # Single monitor setup
  bspc monitor -d 1st 2nd 3rd terms conf
else
  bspc monitor ${MONITORS[0]} -d main files apps
  bspc monitor ${MONITORS[1]} -d 1st 2nd 3rd terms conf
fi
