POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir virtualenv vcs)
#POWERLEVEL9K_CONTEXT_TEMPLATE=
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status ssh root_indicator background_jobs time)

#POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'
# Limit to the last two folders
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

POWERLEVEL9K_ANACONDA_LEFT_DELIMITER='('
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=')'

#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_CROSS=true
