#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15

yabai -m config external_bar all:38:0

yabai -m config mouse_modifier ctrl

yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move

# yabai -m space 1 --label main
# yabai -m space 2 --label docs
# yabai -m space 3 --label comms

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Exclusions
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^zoom.us" manage=off

# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
