#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config layout bsp

yabai -m config top_padding    40
yabai -m config bottom_padding 20
yabai -m config left_padding   20
yabai -m config right_padding  20
yabai -m config window_gap     20

yabai -m config mouse_modifier alt

yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move


yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Exclusions
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^zoom.us" manage=off

# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'"
