[metadata]
name = "dirs"
description = "A channel to select from directories"
requirements = ["fd"]

[source]
command = ["fd -t d --follow", "fd -t d --hidden --follow"]

[preview]
command = "ls -la --color=always '{}'"

[keybindings]
shortcut = "f2"
