---
version: 2
# Enable to debug issues
# log-file: /tmp/efm.log
# log-level: 1

root-markers:
  - package.json
  - .git

tools:
  caddy-fmt: &caddy-fmt
    format-command: "caddy fmt"

  eslint_d: &eslint_d
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  htmlbeautifier: &htmlbeautifier
    format-command: "htmlbeautifier --tab-stops 2"
    format-stdin: true

  lua-selene: &lua-selene
    lint-command: >-
      selene --display-style quiet
      --config "~/.config/selene/selene.toml"
      ${INPUT}
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %tarning%m"
      - "%f:%l:%c: %trror%m"

  lua-stylua: &lua-stylua
    format-command: >-
      stylua
      --stdin-filepath "${INPUT}"
      --search-parent-directories
      -
    format-stdin: true

  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -i 2 -ci -s -bn'
    format-stdin: true

  rustywind: &rustywind
    format-command: "rustywind --stdin"
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  caddyfile:
    # Disabled because it doesn't play well with jinja2 variable templating in
    # ansible
    # - <<: *caddy-fmt

  eelixir:
    - <<: *htmlbeautifier

  graphql:
    - <<: *prettier

  lua:
    - <<: *lua-stylua
    # Disabled because it doesn't seem to recognize `vim` global.
    #- <<: *lua-selene

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  json:
    - <<: *prettier

  javascript:
    - <<: *eslint_d
    - <<: *prettier

  javascriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind

  typescript:
    - <<: *eslint_d
    - <<: *prettier

  typescriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind

  yaml:
    - <<: *yaml-yamllint
