version: 2

root-markers:
  - package.json
  - .git

tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format --tab-width=2 --indent-width=2 --no-chop-down-table --extra-sep-at-table-end --no-keep-simple-control-block-one-line --no-keep-simple-function-one-line -i'
    format-stdin: true

  mix_credo: &mix_credo
    lint-command: "MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
    root-markers:
      - mix.lock
      - mix.exs

  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  rustywind: &rustywind
    format-command: "rustywind --stdin"
    format-stdin: true

languages:
  lua:
    - <<: *lua-lua-format

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  elixir:
    - <<: *mix_credo

  json:
    - <<: *prettier

  javascript:
    - <<: *eslint_d
    - <<: *prettier

  javascriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind

  typescript:
    - <<: *eslint_d

  typescriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind
