---
version: 2

root-markers:
  - package.json
  - .git

tools:
  eslint_d: &eslint_d
    lint-command: 'eslint_d -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  htmlbeautifier: &htmlbeautifier
    format-command: "htmlbeautifier --tab-stops 2"
    format-stdin: true

  lua-selene: &lua-selene
    lint-command: >-
      selene --display-style quiet
      --config "${HOME}/.config/selene/selene.toml"
      ${INPUT}
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %tarning%m"
      - "%f:%l:%c: %trror%m"

  lua-lua-format: &lua-lua-format
    format-command: >-
      lua-format
      --no-use-tab
      --column-limit=100
      --column-table-limit=80
      --indent-width=2
      --break-after-functioncall-lp
      --break-before-functioncall-rp
      --spaces-inside-table-braces
      --chop-down-parameter
      --chop-down-table
      --chop-down-kv-table
      --extra-sep-at-table-end
      --no-keep-simple-control-block-one-line
      --no-keep-simple-function-one-line
      -i
    format-stdin: true

  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -i 2 -ci -s -bn'
    format-stdin: true

  rustywind: &rustywind
    format-command: "rustywind --stdin"
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

languages:
  eelixir:
    - <<: *htmlbeautifier

  graphql:
    - <<: *prettier

  lua:
    - <<: *lua-lua-format
    # Disabled because it doesn't seem to recognize `vim` global.
    #- <<: *lua-selene

  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt

  json:
    - <<: *prettier

  javascript:
    - <<: *eslint_d
    - <<: *prettier

  javascriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind

  typescript:
    - <<: *eslint_d
    - <<: *prettier

  typescriptreact:
    - <<: *eslint_d
    - <<: *prettier
    - <<: *rustywind

  yaml:
    - <<: *yaml-yamllint
