name: Check Build

on: push

jobs:
  check:
    name: Check Nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true

      - name: Check Nixpkgs Inputs
        uses: DeterminateSystems/flake-checker-action@v5

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}

      - name: Nix flake check
        run: nix flake check

      - name: Statix analysis
        run: nix run .#statix -- check
